name: Setup Terraform
description: Setup Terraform with provider caching and AWS credentials

inputs:
  layer:
    description: 'Layer name (10_core, 20_infra, 30_app)'
    required: true
  environment:
    description: 'Environment (dev, stage, prod)'
    required: true
  terraform-version:
    description: 'Terraform version to install'
    required: false
    default: '~> 1.5.0'
  aws-role-arn:
    description: 'AWS IAM role ARN to assume'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  run-id:
    description: 'GitHub run ID for session naming'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    - name: Cache Terraform providers
      uses: actions/cache@v4
      with:
        path: |
          ~/.terraform.d/plugins
          practice/deploy/${{ inputs.layer }}/environments/${{ inputs.environment }}/.terraform
        key: ${{ runner.os }}-terraform-${{ inputs.layer }}-${{ inputs.environment }}-${{ hashFiles(format('practice/deploy/{0}/**/versions.tf', inputs.layer), format('practice/deploy/{0}/**/providers.tf', inputs.layer)) }}
        restore-keys: |
          ${{ runner.os }}-terraform-${{ inputs.layer }}-${{ inputs.environment }}-
          ${{ runner.os }}-terraform-${{ inputs.layer }}-
          ${{ runner.os }}-terraform-

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: GitHubActions-Terraform-${{ inputs.run-id }}
