name: Terraform Plan
description: Initialize Terraform, validate configuration, and generate execution plan

inputs:
  layer:
    description: 'Layer name (10_core, 20_infra, 30_app)'
    required: true
  environment:
    description: 'Environment (dev, stage, prod)'
    required: true
  backend-bucket:
    description: 'S3 backend bucket name'
    required: true
  lock-timeout:
    description: 'Lock timeout duration'
    required: false
    default: '30s'
  save-plan:
    description: 'Whether to save plan file'
    required: false
    default: 'false'

outputs:
  plan_exit_code:
    description: 'Exit code from terraform plan'
    value: ${{ steps.terraform-plan.outputs.exit_code }}

runs:
  using: composite
  steps:
    - name: Terraform Init
      shell: bash
      working-directory: practice/deploy/${{ inputs.layer }}/environments/${{ inputs.environment }}
      run: |
        terraform init -backend-config="bucket=${{ inputs.backend-bucket }}"

    - name: Terraform Validate
      shell: bash
      working-directory: practice/deploy/${{ inputs.layer }}/environments/${{ inputs.environment }}
      run: terraform validate

    - name: Terraform Plan
      id: terraform-plan
      shell: bash
      working-directory: practice/deploy/${{ inputs.layer }}/environments/${{ inputs.environment }}
      run: |
        echo "Running terraform plan for ${{ inputs.layer }} layer..."

        if [ "${{ inputs.save-plan }}" = "true" ]; then
          terraform plan -no-color -out=tfplan -lock-timeout=${{ inputs.lock-timeout }} > plan_output.txt 2>&1
        else
          terraform plan -no-color -lock-timeout=${{ inputs.lock-timeout }} > plan_output.txt 2>&1
        fi

        PLAN_EXIT_CODE=${PIPESTATUS[0]}
        echo "exit_code=$PLAN_EXIT_CODE" >> $GITHUB_OUTPUT

        echo "=== Terraform Plan Output ==="
        cat plan_output.txt
        echo "=== End Plan Output ==="

        if [ $PLAN_EXIT_CODE -ne 0 ]; then
          echo "::error::Terraform plan failed with exit code $PLAN_EXIT_CODE"
          echo "Last 50 lines of plan output:"
          tail -50 plan_output.txt || cat plan_output.txt
          exit $PLAN_EXIT_CODE
        fi
